# Generated by Django 5.1.4 on 2025-01-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('focal_point', 'Focal Point'), ('general_secretary', 'General Secretary'), ('president', 'President'), ('superuser', 'Superuser')], default='member', max_length=20),
        ),
    ]
