# Generated by Django 5.1.4 on 2025-01-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clubmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='designation',
            field=models.CharField(choices=[('administration', 'Administration'), ('finance_accounting', 'Finance & Accounting'), ('program', 'Program'), ('news', 'News'), ('engineering', 'Engineering'), ('design', 'Design'), ('licensing', 'Licensing'), ('camera', 'Camera'), ('information_technology', 'Information Technology (IT)'), ('sales', 'Sales'), ('security', 'Security')], max_length=50),
        ),
    ]
