# Generated by Django 5.1.4 on 2025-01-21 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_clubmember_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
