# Generated by Django 5.1.4 on 2025-01-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_clubmember_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('administration', 'Administration'), ('finance_accounting', 'Finance & Accounting'), ('program', 'Program'), ('news', 'News'), ('engineering', 'Engineering'), ('design', 'Design'), ('licensing', 'Licensing'), ('camera', 'Camera'), ('information_technology', 'Information Technology (IT)'), ('sales', 'Sales'), ('security', 'Security')], default='member', max_length=50),
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='department',
            field=models.CharField(choices=[('administration', 'Administration'), ('finance_accounting', 'Finance & Accounting'), ('program', 'Program'), ('news', 'News'), ('engineering', 'Engineering'), ('design', 'Design'), ('licensing', 'Licensing'), ('camera', 'Camera'), ('information_technology', 'Information Technology (IT)'), ('sales', 'Sales'), ('security', 'Security')], max_length=100),
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('focal_point', 'Focal Point'), ('general_secretary', 'General Secretary'), ('president', 'President'), ('superuser', 'Superuser')], default='Information Technology (IT)', max_length=20),
        ),
    ]
